### ISSUE TITLE
Max number of attempts reached

### ISSUE THREAD

**Issue by qq1053831109** [miho/MonacoFX#16]
ReferenceError: Can't find variable: monaco
Exception in thread "Thread-19" java.lang.RuntimeException: Cannot initialize editor (JS execution not complete). Max number of attempts reached.
	at eu.mihosoft.monacofx.MonacoFX.lambda$new$1(MonacoFX.java:83)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by qq1053831109** [comment]
it,s my bug code!

**Comment by chqu1012** [comment]
How did you fix that?
